apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev
  annotations: {}
  labels: {}
description: dev
gke:
  cluster: projects/omega-terrain-430406-s9/locations/us-central1-c/clusters/cluster-1

